# Generated by Django 4.2.6 on 2023-10-30 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(default='None', max_length=255, unique=True)),
                ('password', models.CharField(default='', max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
